public class AccountHandler {
    public static void insertAccount(Integer i){
        list<Account> addAccounts = new list<Account>();
        integer N=0;
        while(i>N){
            addAccounts.add(new Account(Name='Acme Inc '+N,AccountNumber='A000n123'));
            N=N+1;
            
        }
        insert addAccounts;
        
       // return ;
        
    }
		public static void insertNewAccount(String str){
            
        }
}